services:
  omeka:
    image: libnamic/omeka-s
    ports:
      - "8081:80"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: omeka_user
      DATABASE_PASSWORD: omeka_password
      DATABASE_DBNAME: omeka_db
    depends_on:
      - db

  db:
    image: mysql:8.0.38
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: omeka_db
      MYSQL_USER: omeka_user
      MYSQL_PASSWORD: omeka_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
